### ISSUE TITLE
use of static variables

### ISSUE THREAD

**Issue by till-s** [areaDetector/ADAravis#16]
I was browsing the code and noticed that there are static (i.e., global) variables [`nConsecutiveBadFrames`](https://github.com/areaDetector/ADAravis/blob/e38f45073f99d4df7a537726598dd6fb90d79646/aravisApp/src/ADAravis.cpp#L249) and [`nBadFramesPrior`](https://github.com/areaDetector/ADAravis/blob/e38f45073f99d4df7a537726598dd6fb90d79646/aravisApp/src/ADAravis.cpp#L274). Probably not a huge problem in practice but I thought I bring it to your attention as it may cause confusion if multiple devices are in use and experiencing problems.

**Comment by MarkRivers** [comment]
@till-s good point, thanks.  I have changed those from static variables to private member variables, set to 0 in the constructor initializer list.
