### ISSUE TITLE
aravis version

### ISSUE THREAD

**Issue by LeeHudsonDLS** [areaDetector/ADAravis#2]
Hi,
I'm sure this isn't an issue more just my lack of understanding so feel free to close. I noticed you've started supporting aravis-0.8, from what I can tell this version hasn't been released yet. Am i mistaken or are you using a beta release or something?

**Comment by MarkRivers** [comment]
This is explained in the RELEASE.md for R1-1.  That was built with the 0_7_2 release.  This gets put into aravis-0.8 directories.  With aravis the even number releases 0.6, 0.8, etc. are the "stable" releases, by which they mean that the API won't change in new versions in that release series.  The odd numbers 0.5, 0.7, etc. are unstable, the API may change.  So 0.7 can be viewed as the development tree for 0.8, and 0.8 should be released soon.  Meanwhile we can use 0.7, but be prepared for API changes.

The reason we can't use 0.6 is that it does not support register caching and that has a huge performance hit for many cameras.  It takes 11 seconds for the camera to be ready after changing any feature, and over 8 minutes to be ready after iocInit.

**Comment by LeeHudsonDLS** [comment]
I understand, I now see the comment in the RELEASE.md file, apologies I didn't spot this. Thanks for the clarification. This 11 second loading time you mentioned when changing a feature, is that only with specific cameras? I can't say i've noticed it with the allied vision cameras.

**Comment by MarkRivers** [comment]
Yes, the 11 seconds was for a FLIR Oryx 10-GBit Ethernet camera which is the worst case I have seen.  For other FLIR GigE cameras it was more like 1.5 seconds, and for the FLIR USB cameras it was very fast, essentially no delay.  I don't know if I measured it with any AVT cameras.
